DECLARE_NET_MESSAGE_BEGIN(CLHandShake, MESSAGE_CL_CONNECT,"dsafsafsa")
DECLARE_NET_MESSAGE_ATOM_VAR(int32,MagicNum)
DECLARE_NET_MESSAGE_ATOM_VAR(int8,QuickMark)		// 定义快速注册的标志
DECLARE_NET_MESSAGE_END(CLHandShake, MESSAGE_CL_CONNECT)