from lexc import *

reserved_packet = {
    'DECLARE_NET_MESSAGE_BEGIN' : 'DECLARE_NET_MESSAGE_BEGIN',
    'DECLARE_NET_MESSAGE_ATOM_VAR' : 'DECLARE_NET_MESSAGE_ATOM_VAR',
    'DECLARE_NET_MESSAGE_END' : 'DECLARE_NET_MESSAGE_END'
}
t_DECLARE_NET_MESSAGE_BEGIN = r'DECLARE_NET_MESSAGE_BEGIN'
t_DECLARE_NET_MESSAGE_ATOM_VAR = r'DECLARE_NET_MESSAGE_ATOM_VAR'
t_DECLARE_NET_MESSAGE_END = r'DECLARE_NET_MESSAGE_END'

reserved.update(reserved_packet)
tokens += reserved_packet.values()

lexer=lex.lex()